name: "Renovate (Dev)"
on:
  pull_request:

env:
    RENOVATE_DRY_RUN: true

jobs:
    renovate-repos-dry-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          
        - name: Self-hosted Renovate
          uses: renovatebot/github-action@2e8e8c59e00d930224943f86f6812fbc6640f454 # v42.0.3
          with:
            token: ${{ secrets.RENOVATE_TOKEN }}
            configurationFile: ./global-renovate-config.json