name: "Renovate (Dev)"
on:
  pull_request:

env:
    RENOVATE_DRY_RUN: true

jobs:
    renovate-repos-dry-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
          
        - name: Self-hosted Renovate
          uses: renovatebot/github-action@eb932558ad942cccfd8211cf535f17ff183a9f74 # v46.1.9
          with:
            token: ${{ secrets.RENOVATE_TOKEN }}
            configurationFile: ./global-renovate-config.json