name: "Renovate (Dev)"
on:
  pull_request:

env:
    RENOVATE_DRY_RUN: true

jobs:
    renovate-repos-dry-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          
        - name: Self-hosted Renovate
          uses: renovatebot/github-action@02f4fdeb479bbb229caa7ad82cb5e691c07e80b3 # v41.0.14
          with:
            token: ${{ secrets.RENOVATE_TOKEN }}
            configurationFile: ./global-renovate-config.json